language: python

notifications:
  email: false

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "cimatosa@gmx.de"

python:
- '3.4'
- '3.5'

before_install:
- sudo apt-get install build-essential
- sudo apt-get install libatlas-base-dev
- which python
- python --version

install:
- pip install pytest pytest-cov
- pip install cython
- pip install numpy scipy
- pip freeze
- python setup.py build_ext --inplace

script:
- py.test tests/ -v -s --cov=stocproc --cov-report term-missing

after_success:
- bash <(curl -s https://codecov.io/bash)
- pip install sphinx
- pip install sphinx_rtd_theme
- cd doc
- openssl aes-256-cbc -K $encrypted_b45fa9d06fcb_key -iv $encrypted_b45fa9d06fcb_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
- mkdir build
- cd build
- git clone https://github.com/cimatosa/stocproc.git --branch gh-pages html
- cd ..
- make html
- cd build/html
- git config user.name "travis gh-pages"
- git config user.email "$COMMIT_AUTHOR_EMAIL"
- git add .
- SHA=`git rev-parse --verify HEAD`
- REPO=`git config remote.origin.url`
- SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
- git commit -m "Deploy to GitHub Pages $SHA"
- git push $SSH_REPO gh-pages
