language: python

notifications:
  email: false

python:
- '3.4'
- '3.5'

before_install:
- sudo apt-get install build-essential
- sudo apt-get install libatlas-base-dev
- which python
- python --version

install:
- pip install pytest pytest-cov
- pip install cython
- pip install numpy scipy
- pip freeze
- python setup.py build_ext --inplace

script:
- py.test tests/ -v --cov=stocproc --cov-report term-missing

after_success:
- bash <(curl -s https://codecov.io/bash)