language: python

notifications:
  email: false

python:
- '2.7'
- '3.4'
- '3.5'

before_install:
- which python
- python --version

install:
- pip install pytest pytest-cov
- pip install python-coveralls
- pip install cython
- pip install numpy scipy
- pip freeze
- python setup.py build_ext --inplace

script:
- py.test tests/ -v --cov=progress --cov-report term-missing

after_success:
- coveralls