language: python
notifications:
  email: false
python:
- '3.4'

before_install:
- sudo apt-get update -qq -y
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
- conda install -y numpy scipy
- which python
- python --version
- python setup.py build_ext --inplace

install:
- pip freeze
script:
- py.test -v tests/
