[tool.poetry]
description = "Generate continuous time stationary stochastic processes from a given auto correlation function."
name = "stocproc"
version = "2.0.0"
authors = ["Richard Hartmann <richard.hartmann@tu-dresden.de>"]
license = "BSD (3 clause)"
classifiers = [
"Operating System :: OS Independent",
"License :: OSI Approved :: BSD License",
"Topic :: Utilities",
"Intended Audience :: Researcher"
]
repository = "https://github.com/cimatosa/stocproc"

[tool.poetry.build]
script = "build.py"
generate-setup-file = true

[tool.poetry.dependencies]
python = "^3.9"
scipy = "^1.7.3"
mpmath = "^1.2.1"
fastcubicspline = "^1.1.5"
numpy = "^1.22.2"
setuptools = "*"
matplotlib = "^3.8.2"  # used in the examples only


[tool.poetry.dev-dependencies]
Cython = "^0.29.25"
black = ">21.12b0"

[build-system]
requires = ["poetry>=0.12", "cython", "setuptools", "numpy"]
build-backend = "poetry.core.masonry.api"
